/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import DAO.ClienteDAO;
import DAO.VendaDAO;
import JSON.LeituraJson;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Joao
 */
public class InternalCadastrarJSon extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalCadastrarJSon
     */
    public InternalCadastrarJSon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaJson = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jTextAreaJson.setColumns(20);
        jTextAreaJson.setRows(5);
        jScrollPane1.setViewportView(jTextAreaJson);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jButton1)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tipoObjetoDeCadastro = "";
        if (jTextAreaJson.getText().contains("anuncio")) {
            tipoObjetoDeCadastro = "vendas";
        } else {
            tipoObjetoDeCadastro = "cliente";
        }
        LeituraJson json = new LeituraJson();
        if (tipoObjetoDeCadastro.equals("cliente")) {
            ClienteDAO clienteDAO = new ClienteDAO();
            clienteDAO.cadastrarCliente(json.lerJsonClientes("[" + jTextAreaJson.getText() + "]"));
        } else if (tipoObjetoDeCadastro.equals("vendas")) {
            VendaDAO vendaDAO = new VendaDAO();
            vendaDAO.insertVenda(json.lerJsonVendas("[" + jTextAreaJson.getText() + "]"));
        }
        jTextAreaJson.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaJson;
    // End of variables declaration//GEN-END:variables
}
