/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.EnviarCodigos;
import Controle.VariaveisDeControle;
import DAO.CodigoDAO;
import DAO.Codigos_has_vendasDAO;
import DAO.ProdutosDAO;
import DAO.VendasPendentesDAO;
import Entidades.Codigos;
import Entidades.Produtos;
import Entidades.VendasPendentes;
import Entidades.codigos_has_vendas;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Joao
 */
public class InternalEnviosManuais extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalEnviosManuais
     */
    private int QtdSelecionadaDaVenda;
    private VendasPendentes ven = new VendasPendentes();
    ArrayList<codigos_has_vendas> listaCodigosHasVendasSelecionados = new ArrayList<>();
    private ArrayList<Codigos> codAdicionadoManualmente = new ArrayList<>();
    private HashMap<String,Produtos> map = VariaveisDeControle.mapProd;

    public InternalEnviosManuais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaCodigosSelecionados = new javax.swing.JTextArea();
        jButtonCarregar = new javax.swing.JButton();
        jSpinnerQTD = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldObservacaoEnvioManual = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldProdutoEnvioManual = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextFieldIdCodigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBoxDialogCodigoManualmente = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextFieldApelidoEnvioManual = new javax.swing.JTextField();
        jSpinnerQTDServer = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Envio de Código");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jTextAreaCodigosSelecionados.setColumns(20);
        jTextAreaCodigosSelecionados.setRows(5);
        jScrollPane7.setViewportView(jTextAreaCodigosSelecionados);

        jButtonCarregar.setText("Carregar");
        jButtonCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarregarActionPerformed(evt);
            }
        });

        jLabel31.setText("Escolher venda:");

        jLabel36.setText("Apelido:");

        jLabel33.setText("Dispositivos:");

        jLabel35.setText("Observação:");

        jLabel32.setText("ID código:");

        jLabel37.setText("Produto:");

        jButton1.setText("Salvar e Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxDialogCodigoManualmente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDialogCodigoManualmenteActionPerformed(evt);
            }
        });

        jButton2.setText("Adicionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Salvar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jSpinnerQTDServer.setValue(ven.getQtd());

        jLabel34.setText("Server:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(176, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxDialogCodigoManualmente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCarregar)
                .addGap(9, 9, 9))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoEnvioManual, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldObservacaoEnvioManual, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldApelidoEnvioManual, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerQTD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerQTDServer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(149, 149, 149))))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jButtonCarregar)
                    .addComponent(jComboBoxDialogCodigoManualmente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProdutoEnvioManual, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldObservacaoEnvioManual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(jLabel36)
                        .addComponent(jTextFieldApelidoEnvioManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(jTextFieldIdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(jSpinnerQTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jLabel34)
                        .addComponent(jSpinnerQTDServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

    }//GEN-LAST:event_formInternalFrameClosed

    private void jButtonCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarregarActionPerformed
        if (VariaveisDeControle.listaCarregando) {
            JOptionPane.showMessageDialog(null, "A lista está sendo carregada, aguarde!");
        } else if (VariaveisDeControle.jComboBoxModelDialogVendasPendentes.getSize() == 0) {
            jComboBoxDialogCodigoManualmente.setModel(VariaveisDeControle.jComboBoxModelDialogVendasPendentes);
            for (int i = 0; i < VariaveisDeControle.listVen.size(); i++) {
                VariaveisDeControle.jComboBoxModelDialogVendasPendentes.insertElementAt(VariaveisDeControle.listVen.get(i), i);
            }
        } else{
            jComboBoxDialogCodigoManualmente.setModel(VariaveisDeControle.jComboBoxModelDialogVendasPendentes);
        }
    }//GEN-LAST:event_jButtonCarregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new Thread(new Runnable() {
            @Override
            public void run() {
                if (listaCodigosHasVendasSelecionados.size() == 0) {
                    JOptionPane.showMessageDialog(null, "Adicione um código");
                } else {
                    ArrayList<codigos_has_vendas> listaCodigosHasVendasSelecionados2 = new ArrayList<>();
                    listaCodigosHasVendasSelecionados2.addAll(listaCodigosHasVendasSelecionados);
                    ArrayList<Codigos> codAdicionadoManualmente2 = new ArrayList<>();
                    codAdicionadoManualmente2.addAll(codAdicionadoManualmente);
                    ven = (VendasPendentes) VariaveisDeControle.jComboBoxModelDialogVendasPendentes.getSelectedItem();
                    ven.setCodigo(null);
                    codAdicionadoManualmente.clear();
                    listaCodigosHasVendasSelecionados.clear();
                    for (Codigos c : codAdicionadoManualmente2) {
                        System.out.println(c.getCodigo() + " na list adicionadoManualmente2");
                    }
                    QtdSelecionadaDaVenda = 0;
                    jTextAreaCodigosSelecionados.setText("");
                    jTextFieldIdCodigo.setText("");
                    jSpinnerQTD.setValue(0);
                    VendasPendentes v = ven;
                    VariaveisDeControle.listVen.remove(v);
                    VariaveisDeControle.jComboBoxModelDialogVendasPendentes.removeElement(v);
                         
                    new EnviarCodigos().enviarCodigoUmaVenda(v, true, codAdicionadoManualmente2, listaCodigosHasVendasSelecionados2);
                    
                    new VendasPendentesDAO().remove(v.getId_venda());
                }
            }
        }).start();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxDialogCodigoManualmenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDialogCodigoManualmenteActionPerformed
        VariaveisDeControle.carregamentoCodigoManual = true;
        ven = (VendasPendentes) jComboBoxDialogCodigoManualmente.getSelectedItem();
        if (ven == null) {
        } else {
            jSpinnerQTD.setValue(ven.getQtd() * map.get(ven.getIdProduto()).getQtd());
            jTextFieldApelidoEnvioManual.setText(ven.getApelido());
            jTextFieldObservacaoEnvioManual.setText(ven.getObservacoes());
            jTextFieldProdutoEnvioManual.setText(ven.getProduto());
        }
    }//GEN-LAST:event_jComboBoxDialogCodigoManualmenteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        QtdSelecionadaDaVenda = QtdSelecionadaDaVenda + (int) jSpinnerQTD.getValue();
        if (QtdSelecionadaDaVenda <= ven.getQtd() * map.get(ven.getIdProduto()).getQtd()) {
            jTextAreaCodigosSelecionados.setText(jTextAreaCodigosSelecionados.getText() + jTextFieldIdCodigo.getText() + " - " + jSpinnerQTD.getValue() + " - " + jSpinnerQTDServer.getValue()  + " server\n");
            inserirEAlterarCodigoVendaManualmente(Integer.parseInt(jTextFieldIdCodigo.getText()), (int) jSpinnerQTD.getValue(), (int) jSpinnerQTDServer.getValue());
        } else {
            JOptionPane.showMessageDialog(null, "Quantidade de dispositivos maior que a da venda");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        listaCodigosHasVendasSelecionados.clear();
        QtdSelecionadaDaVenda = 0;
        jTextAreaCodigosSelecionados.setText("");
        jTextFieldIdCodigo.setText("");
        jSpinnerQTD.setValue(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        VariaveisDeControle.listVen.remove(ven);
        VariaveisDeControle.jComboBoxModelDialogVendasPendentes.removeElement(ven);
        new Thread(new Runnable() {
            @Override
            public void run() {
                if (listaCodigosHasVendasSelecionados.size() == 0) {
                    JOptionPane.showMessageDialog(null, "Adicione um código");
                } else {
                    ArrayList<codigos_has_vendas> listaCodigosHasVendasSelecionados2 = new ArrayList<>();
                    listaCodigosHasVendasSelecionados2.addAll(listaCodigosHasVendasSelecionados);
                    for (codigos_has_vendas chv : listaCodigosHasVendasSelecionados2) {
                        new Codigos_has_vendasDAO().insertCodigoEmVenda(chv);
                        new VendasPendentesDAO().remove(ven.getId_venda());
                    }
                }
            }
        }).start();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
VariaveisDeControle.frameEnvioManualAberto = false;        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonCarregar;
    private javax.swing.JComboBox<String> jComboBoxDialogCodigoManualmente;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSpinner jSpinnerQTD;
    private javax.swing.JSpinner jSpinnerQTDServer;
    private javax.swing.JTextArea jTextAreaCodigosSelecionados;
    private javax.swing.JTextField jTextFieldApelidoEnvioManual;
    private javax.swing.JTextField jTextFieldIdCodigo;
    private javax.swing.JTextField jTextFieldObservacaoEnvioManual;
    private javax.swing.JTextField jTextFieldProdutoEnvioManual;
    // End of variables declaration//GEN-END:variables
  private void inserirEAlterarCodigoVendaManualmente(int id, int qtd, int qtdServer) {
  try{      codigos_has_vendas chv = new codigos_has_vendas();
        chv.setIdVenda(ven.getId_venda());
        chv.setId_codigo(id);
        chv.setQtd(qtd);
        chv.setQtd_servidor(qtdServer);
        listaCodigosHasVendasSelecionados.add(chv);
        Codigos c = new CodigoDAO().buscaUmCodigo(id);
        codAdicionadoManualmente.add(c);
  }catch(Exception e){
      
  }
    }
}
