/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.EnviarCodigos;
import Controle.InsereCodigoNasVendasParaEnvio;
import Controle.VariaveisDeControle;
import DAO.ClienteDAO;
import DAO.VendasPendentesDAO;
import Entidades.Vendas;
import Entidades.VendasPendentes;
import com.email.EmailService;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;

/**
 *
 * @author Joao
 */
public class InternalFrameAnaliseVendaPendentes extends javax.swing.JInternalFrame {

    VendasPendentes ven;

    public InternalFrameAnaliseVendaPendentes() {
        initComponents();
        bloqueiaComponentes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jComboBoxDialogVendasPendentes = new javax.swing.JComboBox<>();
        jTextFieldPagamento = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jButtonSolicitarContato = new javax.swing.JButton();
        jTextFieldObservacoes = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonDeletar = new javax.swing.JButton();
        jTextFieldCodigo = new javax.swing.JTextField();
        jCheckBoxNumeroConfirmado = new javax.swing.JCheckBox();
        jTextFieldApelido = new javax.swing.JTextField();
        jLabelMensagem = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelMensagemProgresso = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldProduto = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonCarregar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setResizable(true);
        setTitle("Análise de Vendas");
        setOpaque(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                closing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel6.setText("Pagamento:");

        jComboBoxDialogVendasPendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDialogVendasPendentesActionPerformed(evt);
            }
        });

        jTextFieldPagamento.setEditable(false);

        jLabel30.setText("Observação:");

        jButtonSolicitarContato.setText("Solicitar Contato");
        jButtonSolicitarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolicitarContatoActionPerformed(evt);
            }
        });

        jTextFieldObservacoes.setEditable(false);

        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        jButtonProximo.setText("Próximo");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jLabel7.setText("Código:");

        jLabel2.setText("Apelido:");

        jButtonDeletar.setText("Excluir");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jTextFieldCodigo.setEditable(false);
        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });

        jCheckBoxNumeroConfirmado.setText("SIM");
        jCheckBoxNumeroConfirmado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNumeroConfirmadoActionPerformed(evt);
            }
        });

        jTextFieldApelido.setEditable(false);

        jLabelMensagem.setText(" ");

        jLabel34.setText("Numero confirmado:");

        jLabel3.setText("Email:");

        jLabelMensagemProgresso.setText(" ");

        jTextFieldEmail.setEditable(false);
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabel5.setText("ID:");

        jTextFieldProduto.setEditable(false);
        jTextFieldProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProdutoActionPerformed(evt);
            }
        });

        jTextFieldId.setEditable(false);

        jLabel4.setText("Produto:");

        jLabel8.setText("Venda Específica:");

        jButtonCarregar.setText("Carregar");
        jButtonCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarregarActionPerformed(evt);
            }
        });

        jMenu1.setText("Opções");

        jMenuItem1.setText("Iniciar Carregamento");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldApelido)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jButtonSolicitarContato)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabelMensagemProgresso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxNumeroConfirmado)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldObservacoes)
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldProduto)
                                        .addComponent(jTextFieldPagamento)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxDialogVendasPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCarregar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxDialogVendasPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCarregar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMensagem)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jTextFieldObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxNumeroConfirmado)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSolicitarContato)
                            .addComponent(jButtonEnviar)
                            .addComponent(jButtonProximo)
                            .addComponent(jButtonDeletar))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMensagemProgresso)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDialogVendasPendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDialogVendasPendentesActionPerformed
        ven = (VendasPendentes) VariaveisDeControle.jComboBoxModelDialogVendasPendentes.getSelectedItem();
        limparCampos();
        if (VariaveisDeControle.jComboBoxModelDialogVendasPendentes.getSelectedItem() == null) {

        } else {
            preencheCamposAnaliseVendas();
        }
    }//GEN-LAST:event_jComboBoxDialogVendasPendentesActionPerformed

    private void jButtonSolicitarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolicitarContatoActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                if (new VendasPendentesDAO().marcaComoPendente(ven.getId_venda(), "Contato solicitado e aguardando")) {
                    limparCampos();
                    VariaveisDeControle.listVen.remove(ven);
                    jLabelMensagemProgresso.setText("");
                    carregarDadosVendasPendentes(false);
                }
            }
        }).start();
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    new EmailService(ven.getEmail(), "Contato Pendente", "Para que seu código seja enviado, por favor entre em contato pelo whastapp 91980452185. Aguardo").sendEmail();
                } catch (IOException ex) {
                    Logger.getLogger(TelaVendas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (MessagingException ex) {
                    Logger.getLogger(TelaVendas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
    }//GEN-LAST:event_jButtonSolicitarContatoActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        VendasPendentes v = ven;
        jLabelMensagemProgresso.setText("Gravando...");
        if (v.getCodigo() == null || v.getIdCodigo() == 0) {
            JOptionPane.showMessageDialog(null, "A venda não pode ser enviada pois não possui código válido");
        } else {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    new EnviarCodigos().enviarCodigoUmaVenda(v, false, null, null);
                }
            }).start();
            jLabelMensagemProgresso.setText("");
            Runnable rr = () -> {
                VariaveisDeControle.listVen.remove(v);
                VariaveisDeControle.jComboBoxModelDialogVendasPendentes.removeElement(v);
                carregarDadosVendasPendentes(false);
            };
            Thread tt = new Thread(rr);
            tt.start();
        }
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        VendasPendentes ven = this.ven;
        limparCampos();
        VariaveisDeControle.listVen.remove(ven);
        VariaveisDeControle.jComboBoxModelDialogVendasPendentes.removeElement(ven);
        jLabelMensagemProgresso.setText("");
        Runnable rr = () -> {
            carregarDadosVendasPendentes(false);
        };
        Thread tt = new Thread(rr);
        tt.start();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        VendasPendentes ven = this.ven;
        int opcao = JOptionPane.showConfirmDialog(null, "Excluir a venda " + ven.getId_venda() + "?", "Excluir venda?", JOptionPane.YES_NO_OPTION);
        if (opcao == 0) {
            limparCampos();
            jLabelMensagemProgresso.setText("");
            System.err.println(ven.getId_venda());
            new VendasPendentesDAO().remove(ven.getId_venda());
            VariaveisDeControle.listVen.remove(ven);
            VariaveisDeControle.jComboBoxModelDialogVendasPendentes.removeElement(ven);
            Runnable rr = () -> {
                carregarDadosVendasPendentes(false);
            };
            Thread tt = new Thread(rr);
            tt.start();
        }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jCheckBoxNumeroConfirmadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNumeroConfirmadoActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Deseja mesmo confirmar o número?", "Confirmar numero", JOptionPane.YES_NO_OPTION);        // TODO add your handling code here:
        if (i == 0) {
            JOptionPane.showMessageDialog(null, "box selecionado");
            System.out.println(ven.getApelido());
            new ClienteDAO().setNumeroConfimado(ven.getApelido());
        }
    }//GEN-LAST:event_jCheckBoxNumeroConfirmadoActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProdutoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        VendasPendentes ven = this.ven;
        if (VariaveisDeControle.listaCarregando) {
            JOptionPane.showMessageDialog(null, "A lista está sendo carregada, aguarde!");
        } else {
            if (VariaveisDeControle.listVen.isEmpty()) {
                new InsereCodigoNasVendasParaEnvio().carregaListaVendasPendentes(true);
                if (!VariaveisDeControle.codigosCarregadosListVen && !VariaveisDeControle.carregandoCodigosNasVendas && VariaveisDeControle.listaCarregando) {
                    new InsereCodigoNasVendasParaEnvio().getCodigosUtilizaveis();
                }
            } else {
                int i = JOptionPane.showConfirmDialog(null, "Deseja carregar a lista novamente?", "Confirmar", JOptionPane.YES_NO_OPTION);
                if (i == 0) {
                    VariaveisDeControle.carregarVendasPendentesECodigos();
                } 
            }
        }
        if(VariaveisDeControle.listVen.isEmpty()){
            JOptionPane.showMessageDialog(null, "Não há vendas pendentes no momento!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarregarActionPerformed
        if (VariaveisDeControle.listaCarregando) {
            JOptionPane.showMessageDialog(null, "A lista está sendo carregada, aguarde!");
        } else if (VariaveisDeControle.jComboBoxModelDialogVendasPendentes.getSize() == 0) {
            jComboBoxDialogVendasPendentes.setModel(VariaveisDeControle.jComboBoxModelDialogVendasPendentes);
            for (int i = 0; i < VariaveisDeControle.listVen.size(); i++) {
                VariaveisDeControle.jComboBoxModelDialogVendasPendentes.insertElementAt(VariaveisDeControle.listVen.get(i), i);
            }
            desbloqueiaComponentes();
        } else {
            jComboBoxDialogVendasPendentes.setModel(VariaveisDeControle.jComboBoxModelDialogVendasPendentes);
            desbloqueiaComponentes();
        }
    }//GEN-LAST:event_jButtonCarregarActionPerformed

    private void closing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_closing
        VariaveisDeControle.frameAnaliseVendasAberto = false;
    }//GEN-LAST:event_closing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCarregar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSolicitarContato;
    private javax.swing.JCheckBox jCheckBoxNumeroConfirmado;
    private javax.swing.JComboBox<String> jComboBoxDialogVendasPendentes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JLabel jLabelMensagemProgresso;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField jTextFieldApelido;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldObservacoes;
    private javax.swing.JTextField jTextFieldPagamento;
    private javax.swing.JTextField jTextFieldProduto;
    // End of variables declaration//GEN-END:variables

    public void carregarDadosVendasPendentes(boolean primeiroCarregamento) {
        if (!VariaveisDeControle.listaCarregando) {

            if (!VariaveisDeControle.listVen.isEmpty()) {
                System.out.println("List isEmpty: " + VariaveisDeControle.listVen.isEmpty());
                ven = VariaveisDeControle.listVen.get(0);
                jComboBoxDialogVendasPendentes.setSelectedIndex(0);
                System.out.println(ven);

                if (VariaveisDeControle.carregamentoCodigoManual) {
                    VariaveisDeControle.carregamentoCodigoManual = false;
                }
                preencheCamposAnaliseVendas();
                desbloqueiaComponentes();

            } else {
                if (VariaveisDeControle.listaCarregando) {
                    // não remover este método. enquanto a lista estiver carregando, listaCarregando será
                    // false e não vai exibir a mensaguem "Não há vendas"
                } else {
                    JOptionPane.showMessageDialog(null, "Não há vendas pendentes no momento");
                    VariaveisDeControle.codigosCarregadosListVen = false;
                    VariaveisDeControle.listVen.clear();
                    VariaveisDeControle.jComboBoxModelDialogVendasPendentes.removeAllElements();
                    bloqueiaComponentes();
                }
            }
        }
    }

    private void desbloqueiaComponentes() {
        jButtonEnviar.setEnabled(true);
        jButtonSolicitarContato.setEnabled(true);
        jButtonProximo.setEnabled(true);
        jButtonDeletar.setEnabled(true);
        jComboBoxDialogVendasPendentes.setEnabled(true);
    }

    private void bloqueiaComponentes() {
        jComboBoxDialogVendasPendentes.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonSolicitarContato.setEnabled(false);
        jButtonEnviar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
    }

    private void limparCampos() {
        jLabelMensagemProgresso.setText("");
        jLabelMensagem.setText("");
        jTextFieldApelido.setText("");
        jTextFieldId.setText("");
        jTextFieldEmail.setText("");
        jTextFieldProduto.setText("");
        jTextFieldPagamento.setText("");
        jTextFieldCodigo.setText("");
        jTextFieldObservacoes.setText("");
        jCheckBoxNumeroConfirmado.setSelected(false);
    }

    private void preencheCamposAnaliseVendas() {
        limparCampos();
        jTextFieldObservacoes.setText(ven.getObservacoes());
        jTextFieldApelido.setText(ven.getApelido());
        jTextFieldEmail.setText(ven.getEmail());
        jTextFieldProduto.setText(ven.getProduto());
        jTextFieldPagamento.setText(ven.getPagamento());
        jTextFieldCodigo.setText(ven.getCodigo());
        jTextFieldId.setText(ven.getId_venda());
    }

}
