/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.VariaveisDeControle;
import DAO.ProdutosDAO;
import DAO.VendaDAO;
import Entidades.Vendas;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Joao
 */
public class InternalCadastroVendaOutrosMeios extends javax.swing.JInternalFrame {

    private Vendas venCadOutAquisicoes = new Vendas();

    /**
     * Creates new form internalCadastroVendaOutrosMeios
     */
    public InternalCadastroVendaOutrosMeios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPagamento = new javax.swing.ButtonGroup();
        buttonGroupAquisicao = new javax.swing.ButtonGroup();
        buttonGroupDataVenda = new javax.swing.ButtonGroup();
        buttonGroupTipo = new javax.swing.ButtonGroup();
        buttonGroupServer = new javax.swing.ButtonGroup();
        jPanelCadastroVenda_quatidade = new javax.swing.JPanel();
        jTextFieldQtd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldDispositivos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanelCadastroVenda_pagamento = new javax.swing.JPanel();
        jComboBoxPagamento = new javax.swing.JComboBox<>();
        jPanelCadastroVenda_aquisicao = new javax.swing.JPanel();
        jComboBoxAquisicao = new javax.swing.JComboBox<>();
        jPanelCadastroVenda_anos = new javax.swing.JPanel();
        jComboBoxAnos = new javax.swing.JComboBox<>();
        jPanelCadastroVenda_cliente = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldApelidoCadastraVendaWhatsapp = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanelCadastroVenda_tipo = new javax.swing.JPanel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jPanelCadastroVenda_data = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jPanelServidores = new javax.swing.JPanel();
        jComboBoxServidores = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastrar Venda");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanelCadastroVenda_quatidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade"));

        jTextFieldQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQtdActionPerformed(evt);
            }
        });

        jLabel9.setText("Valor:");

        jLabel10.setText("Dispositivos:");

        jTextFieldDispositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDispositivosActionPerformed(evt);
            }
        });

        jLabel12.setText("Quantidade:");

        javax.swing.GroupLayout jPanelCadastroVenda_quatidadeLayout = new javax.swing.GroupLayout(jPanelCadastroVenda_quatidade);
        jPanelCadastroVenda_quatidade.setLayout(jPanelCadastroVenda_quatidadeLayout);
        jPanelCadastroVenda_quatidadeLayout.setHorizontalGroup(
            jPanelCadastroVenda_quatidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroVenda_quatidadeLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDispositivos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanelCadastroVenda_quatidadeLayout.setVerticalGroup(
            jPanelCadastroVenda_quatidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_quatidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroVenda_quatidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldDispositivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelCadastroVenda_pagamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento"));

        jComboBoxPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deposito", "Mercado Pago" }));
        jComboBoxPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroVenda_pagamentoLayout = new javax.swing.GroupLayout(jPanelCadastroVenda_pagamento);
        jPanelCadastroVenda_pagamento.setLayout(jPanelCadastroVenda_pagamentoLayout);
        jPanelCadastroVenda_pagamentoLayout.setHorizontalGroup(
            jPanelCadastroVenda_pagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_pagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadastroVenda_pagamentoLayout.setVerticalGroup(
            jPanelCadastroVenda_pagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroVenda_pagamentoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelCadastroVenda_aquisicao.setBorder(javax.swing.BorderFactory.createTitledBorder("Aquisição"));

        jComboBoxAquisicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Whatsapp", "Email", "Brinde" }));

        javax.swing.GroupLayout jPanelCadastroVenda_aquisicaoLayout = new javax.swing.GroupLayout(jPanelCadastroVenda_aquisicao);
        jPanelCadastroVenda_aquisicao.setLayout(jPanelCadastroVenda_aquisicaoLayout);
        jPanelCadastroVenda_aquisicaoLayout.setHorizontalGroup(
            jPanelCadastroVenda_aquisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_aquisicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadastroVenda_aquisicaoLayout.setVerticalGroup(
            jPanelCadastroVenda_aquisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroVenda_aquisicaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelCadastroVenda_anos.setBorder(javax.swing.BorderFactory.createTitledBorder("Anos"));

        jComboBoxAnos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        javax.swing.GroupLayout jPanelCadastroVenda_anosLayout = new javax.swing.GroupLayout(jPanelCadastroVenda_anos);
        jPanelCadastroVenda_anos.setLayout(jPanelCadastroVenda_anosLayout);
        jPanelCadastroVenda_anosLayout.setHorizontalGroup(
            jPanelCadastroVenda_anosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_anosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jComboBoxAnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanelCadastroVenda_anosLayout.setVerticalGroup(
            jPanelCadastroVenda_anosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_anosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxAnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCadastroVenda_cliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel13.setText("Apelido:");

        jTextFieldApelidoCadastraVendaWhatsapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApelidoCadastraVendaWhatsappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroVenda_clienteLayout = new javax.swing.GroupLayout(jPanelCadastroVenda_cliente);
        jPanelCadastroVenda_cliente.setLayout(jPanelCadastroVenda_clienteLayout);
        jPanelCadastroVenda_clienteLayout.setHorizontalGroup(
            jPanelCadastroVenda_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_clienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldApelidoCadastraVendaWhatsapp, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCadastroVenda_clienteLayout.setVerticalGroup(
            jPanelCadastroVenda_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroVenda_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldApelidoCadastraVendaWhatsapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jButton3.setText("Cadastrar Venda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanelCadastroVenda_tipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "KIS", "ANDROID", "TOTAL", "SMALL" }));
        jComboBoxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroVenda_tipoLayout = new javax.swing.GroupLayout(jPanelCadastroVenda_tipo);
        jPanelCadastroVenda_tipo.setLayout(jPanelCadastroVenda_tipoLayout);
        jPanelCadastroVenda_tipoLayout.setHorizontalGroup(
            jPanelCadastroVenda_tipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_tipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadastroVenda_tipoLayout.setVerticalGroup(
            jPanelCadastroVenda_tipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroVenda_tipoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelCadastroVenda_data.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        buttonGroupDataVenda.add(jRadioButton5);
        jRadioButton5.setText("Hoje");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroupDataVenda.add(jRadioButton6);
        jRadioButton6.setText("Outro dia");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroVenda_dataLayout = new javax.swing.GroupLayout(jPanelCadastroVenda_data);
        jPanelCadastroVenda_data.setLayout(jPanelCadastroVenda_dataLayout);
        jPanelCadastroVenda_dataLayout.setHorizontalGroup(
            jPanelCadastroVenda_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_dataLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jRadioButton5)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton6)
                .addGap(24, 24, 24))
        );
        jPanelCadastroVenda_dataLayout.setVerticalGroup(
            jPanelCadastroVenda_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroVenda_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelServidores.setBorder(javax.swing.BorderFactory.createTitledBorder("Servidores"));

        jComboBoxServidores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "0" }));
        jComboBoxServidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServidoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelServidoresLayout = new javax.swing.GroupLayout(jPanelServidores);
        jPanelServidores.setLayout(jPanelServidoresLayout);
        jPanelServidoresLayout.setHorizontalGroup(
            jPanelServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServidoresLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jComboBoxServidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelServidoresLayout.setVerticalGroup(
            jPanelServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServidoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxServidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jPanelCadastroVenda_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelCadastroVenda_aquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelCadastroVenda_pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelCadastroVenda_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelCadastroVenda_anos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelServidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelCadastroVenda_quatidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelCadastroVenda_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCadastroVenda_aquisicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCadastroVenda_pagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCadastroVenda_tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCadastroVenda_anos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelServidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCadastroVenda_quatidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCadastroVenda_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelCadastroVenda_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton3)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQtdActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQtdActionPerformed

    private void jTextFieldDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDispositivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDispositivosActionPerformed

    private void jTextFieldApelidoCadastraVendaWhatsappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApelidoCadastraVendaWhatsappActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApelidoCadastraVendaWhatsappActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean ok = true;
        
        if (jComboBoxTipo.getSelectedIndex()==0) {
            jPanelCadastroVenda_tipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0)));
            ok = false;
        } else {
            jPanelCadastroVenda_tipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
            ok = true;
        }
        if (jComboBoxAnos.getSelectedIndex()==0) {
            jPanelCadastroVenda_anos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Anos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0)));
            ok = false;
        } else {
            jPanelCadastroVenda_anos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Anos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
            ok = true;
        }
        
        
        if (buttonGroupDataVenda.getSelection() == null) {
            jPanelCadastroVenda_data.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0)));
            ok = false;
        } else {
            jPanelCadastroVenda_data.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
            ok = true;
        }
        if (jTextFieldQtd.getText().equals("") || jTextFieldValor.getText().equals("") || jTextFieldDispositivos.getText().equals("")) {
            jPanelCadastroVenda_quatidade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quantidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0)));
            ok = false;
        } else {
            jPanelCadastroVenda_quatidade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quantidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
            ok = true;
        }
        if (VariaveisDeControle.frameCadastroClienteAberto) {

        }
        if (ok) {
            new Thread(() -> {
                VendaDAO vDao = new VendaDAO();
                String idProduto = "";
                if (jComboBoxTipo.getSelectedItem().equals("SMALL")) {
                    idProduto = jComboBoxTipo.getSelectedItem() + jTextFieldDispositivos.getText() + "D" + jComboBoxServidores.getSelectedItem() +"S" + jComboBoxAnos.getSelectedItem() + "A";
                } else{
                idProduto = jComboBoxTipo.getSelectedItem() + jTextFieldDispositivos.getText() + "D" + jComboBoxAnos.getSelectedItem() + "A";
                }
                venCadOutAquisicoes.setIdProduto(idProduto);
                venCadOutAquisicoes.setApelido_comprador(jTextFieldApelidoCadastraVendaWhatsapp.getText());
                venCadOutAquisicoes.setValor(Double.parseDouble(jTextFieldValor.getText()));
                venCadOutAquisicoes.setCadastroVendedor(1);
                venCadOutAquisicoes.setFormaAquisicao((String) jComboBoxAquisicao.getSelectedItem());
                venCadOutAquisicoes.setFormaPagamento((String) jComboBoxPagamento.getSelectedItem());
                venCadOutAquisicoes.setId(vDao.getCountVendasWhatsappDoDia());
                venCadOutAquisicoes.setQtd(Integer.parseInt(jTextFieldQtd.getText()));
                venCadOutAquisicoes.setValor(Double.parseDouble(jTextFieldValor.getText()));
                venCadOutAquisicoes.setHora(new Time(System.currentTimeMillis()) + "");
                vDao.insertVendas(venCadOutAquisicoes);
            }).start();
        } else {
            JOptionPane.showMessageDialog(null, "Verifique os campos em vermelho e preencha");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        Date data = new Date(System.currentTimeMillis());
        SimpleDateFormat formatarDate = new SimpleDateFormat("yyyy-MM-dd");
        venCadOutAquisicoes.setData(formatarDate.format(data));        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        venCadOutAquisicoes.setData(JOptionPane.showInputDialog("Qual dia? 'AAAA-MM-DD'"));        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        VariaveisDeControle.frameCadVenOutroMeioAberto = false;        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing

    private void jComboBoxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoItemStateChanged
        int contador = 0;
        if (contador == 0) {
            contador = 1;
            String tipo = (String) jComboBoxTipo.getSelectedItem();
            switch (tipo) {
                case "SMALL":
                     jComboBoxServidores.setEnabled(true);
                     jComboBoxAnos.removeAllItems();
                     jComboBoxAnos.addItem("1");
                     jComboBoxAnos.addItem("2");
                    break;
                case "KIS":
                    jComboBoxServidores.setEnabled(false);
                    jComboBoxAnos.removeAllItems();
                    jComboBoxAnos.addItem("1");
                    break;
                case "TOTAL":
                     jComboBoxServidores.setEnabled(false);
                     jComboBoxAnos.removeAllItems();
                     jComboBoxAnos.addItem("1");
                     jComboBoxAnos.addItem("2");
                     jComboBoxAnos.addItem("3");
                     jComboBoxAnos.addItem("4");
                     jComboBoxAnos.addItem("5");
                    break;
                case "ANDROID":
                     jComboBoxServidores.setEnabled(false);
                     jComboBoxAnos.removeAllItems();
                     jComboBoxAnos.addItem("1");
                    break;
            }
        }
    }//GEN-LAST:event_jComboBoxTipoItemStateChanged

    private void jComboBoxPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPagamentoActionPerformed

    private void jComboBoxServidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServidoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxServidoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAquisicao;
    private javax.swing.ButtonGroup buttonGroupDataVenda;
    private javax.swing.ButtonGroup buttonGroupPagamento;
    private javax.swing.ButtonGroup buttonGroupServer;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxAnos;
    private javax.swing.JComboBox<String> jComboBoxAquisicao;
    private javax.swing.JComboBox<String> jComboBoxPagamento;
    private javax.swing.JComboBox<String> jComboBoxServidores;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCadastroVenda_anos;
    private javax.swing.JPanel jPanelCadastroVenda_aquisicao;
    private javax.swing.JPanel jPanelCadastroVenda_cliente;
    private javax.swing.JPanel jPanelCadastroVenda_data;
    private javax.swing.JPanel jPanelCadastroVenda_pagamento;
    private javax.swing.JPanel jPanelCadastroVenda_quatidade;
    private javax.swing.JPanel jPanelCadastroVenda_tipo;
    private javax.swing.JPanel jPanelServidores;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextFieldApelidoCadastraVendaWhatsapp;
    private javax.swing.JTextField jTextFieldDispositivos;
    private javax.swing.JTextField jTextFieldQtd;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
