/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.VariaveisDeControle;
import DAO.ProdutosDAO;
import DAO.VendaDAO;
import Entidades.Vendas;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Joao
 */
public class InternalCadastroVendaOutrosMeios extends javax.swing.JInternalFrame {

    private Vendas venCadOutAquisicoes = new Vendas();
    private int anoProduto;
    private String tipoDeProduto;

    /**
     * Creates new form internalCadastroVendaOutrosMeios
     */
    public InternalCadastroVendaOutrosMeios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPagamento = new javax.swing.ButtonGroup();
        buttonGroupAquisicao = new javax.swing.ButtonGroup();
        buttonGroupDataVenda = new javax.swing.ButtonGroup();
        buttonGroupAnos = new javax.swing.ButtonGroup();
        buttonGroupTipo = new javax.swing.ButtonGroup();
        jPanelCadastroVenda_quatidade = new javax.swing.JPanel();
        jTextFieldQtd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldDispositivos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanelCadastroVenda_pagamento = new javax.swing.JPanel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jPanelCadastroVenda_aquisicao = new javax.swing.JPanel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jPanelCadastroVenda_anos = new javax.swing.JPanel();
        jRadioButton3anos = new javax.swing.JRadioButton();
        jRadioButton2anos = new javax.swing.JRadioButton();
        jRadioButton1ano = new javax.swing.JRadioButton();
        jPanelCadastroVenda_cliente = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldApelidoCadastraVendaWhatsapp = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanelCadastroVenda_tipo = new javax.swing.JPanel();
        jRadioButtonKIS = new javax.swing.JRadioButton();
        jRadioButtonAndroid = new javax.swing.JRadioButton();
        jRadioButtonSmall = new javax.swing.JRadioButton();
        jRadioButtonTotal = new javax.swing.JRadioButton();
        jPanelCadastroVenda_data = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastrar Venda");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanelCadastroVenda_quatidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade"));

        jTextFieldQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQtdActionPerformed(evt);
            }
        });

        jLabel9.setText("Valor:");

        jLabel10.setText("Dispositivos:");

        jTextFieldDispositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDispositivosActionPerformed(evt);
            }
        });

        jLabel12.setText("Quantidade:");

        javax.swing.GroupLayout jPanelCadastroVenda_quatidadeLayout = new javax.swing.GroupLayout(jPanelCadastroVenda_quatidade);
        jPanelCadastroVenda_quatidade.setLayout(jPanelCadastroVenda_quatidadeLayout);
        jPanelCadastroVenda_quatidadeLayout.setHorizontalGroup(
            jPanelCadastroVenda_quatidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroVenda_quatidadeLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(2, 2, 2)
                .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDispositivos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCadastroVenda_quatidadeLayout.setVerticalGroup(
            jPanelCadastroVenda_quatidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_quatidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroVenda_quatidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldDispositivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelCadastroVenda_pagamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento"));

        buttonGroupPagamento.add(jRadioButton8);
        jRadioButton8.setText("Mercado Pago");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        buttonGroupPagamento.add(jRadioButton7);
        jRadioButton7.setText("Deposito");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroVenda_pagamentoLayout = new javax.swing.GroupLayout(jPanelCadastroVenda_pagamento);
        jPanelCadastroVenda_pagamento.setLayout(jPanelCadastroVenda_pagamentoLayout);
        jPanelCadastroVenda_pagamentoLayout.setHorizontalGroup(
            jPanelCadastroVenda_pagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_pagamentoLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jRadioButton7)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton8)
                .addGap(10, 10, 10))
        );
        jPanelCadastroVenda_pagamentoLayout.setVerticalGroup(
            jPanelCadastroVenda_pagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_pagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroVenda_pagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCadastroVenda_aquisicao.setBorder(javax.swing.BorderFactory.createTitledBorder("Aquisição"));

        buttonGroupAquisicao.add(jRadioButton9);
        jRadioButton9.setText("Whatsapp");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        buttonGroupAquisicao.add(jRadioButton10);
        jRadioButton10.setText("Email");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroVenda_aquisicaoLayout = new javax.swing.GroupLayout(jPanelCadastroVenda_aquisicao);
        jPanelCadastroVenda_aquisicao.setLayout(jPanelCadastroVenda_aquisicaoLayout);
        jPanelCadastroVenda_aquisicaoLayout.setHorizontalGroup(
            jPanelCadastroVenda_aquisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_aquisicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jRadioButton10))
        );
        jPanelCadastroVenda_aquisicaoLayout.setVerticalGroup(
            jPanelCadastroVenda_aquisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroVenda_aquisicaoLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanelCadastroVenda_aquisicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10))
                .addContainerGap())
        );

        jPanelCadastroVenda_anos.setBorder(javax.swing.BorderFactory.createTitledBorder("Anos"));

        buttonGroupAnos.add(jRadioButton3anos);
        jRadioButton3anos.setText("3 anos");
        jRadioButton3anos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3anosActionPerformed(evt);
            }
        });

        buttonGroupAnos.add(jRadioButton2anos);
        jRadioButton2anos.setText("2 anos");
        jRadioButton2anos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2anosActionPerformed(evt);
            }
        });

        buttonGroupAnos.add(jRadioButton1ano);
        jRadioButton1ano.setText("1 ano");
        jRadioButton1ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1anoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroVenda_anosLayout = new javax.swing.GroupLayout(jPanelCadastroVenda_anos);
        jPanelCadastroVenda_anos.setLayout(jPanelCadastroVenda_anosLayout);
        jPanelCadastroVenda_anosLayout.setHorizontalGroup(
            jPanelCadastroVenda_anosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_anosLayout.createSequentialGroup()
                .addComponent(jRadioButton1ano)
                .addGap(8, 8, 8)
                .addComponent(jRadioButton2anos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3anos, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCadastroVenda_anosLayout.setVerticalGroup(
            jPanelCadastroVenda_anosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_anosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroVenda_anosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1ano)
                    .addComponent(jRadioButton2anos)
                    .addComponent(jRadioButton3anos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCadastroVenda_cliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel13.setText("Apelido:");

        jTextFieldApelidoCadastraVendaWhatsapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApelidoCadastraVendaWhatsappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroVenda_clienteLayout = new javax.swing.GroupLayout(jPanelCadastroVenda_cliente);
        jPanelCadastroVenda_cliente.setLayout(jPanelCadastroVenda_clienteLayout);
        jPanelCadastroVenda_clienteLayout.setHorizontalGroup(
            jPanelCadastroVenda_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldApelidoCadastraVendaWhatsapp, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelCadastroVenda_clienteLayout.setVerticalGroup(
            jPanelCadastroVenda_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroVenda_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldApelidoCadastraVendaWhatsapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jButton3.setText("Cadastrar Venda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanelCadastroVenda_tipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));

        buttonGroupTipo.add(jRadioButtonKIS);
        jRadioButtonKIS.setText("KIS");
        jRadioButtonKIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonKISActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(jRadioButtonAndroid);
        jRadioButtonAndroid.setText("Android");
        jRadioButtonAndroid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAndroidActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(jRadioButtonSmall);
        jRadioButtonSmall.setText("Small");
        jRadioButtonSmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSmallActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(jRadioButtonTotal);
        jRadioButtonTotal.setText("Total");
        jRadioButtonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroVenda_tipoLayout = new javax.swing.GroupLayout(jPanelCadastroVenda_tipo);
        jPanelCadastroVenda_tipo.setLayout(jPanelCadastroVenda_tipoLayout);
        jPanelCadastroVenda_tipoLayout.setHorizontalGroup(
            jPanelCadastroVenda_tipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_tipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonKIS)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonAndroid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSmall)
                .addGap(16, 16, 16)
                .addComponent(jRadioButtonTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadastroVenda_tipoLayout.setVerticalGroup(
            jPanelCadastroVenda_tipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_tipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroVenda_tipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonKIS)
                    .addComponent(jRadioButtonAndroid)
                    .addComponent(jRadioButtonSmall)
                    .addComponent(jRadioButtonTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCadastroVenda_data.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        buttonGroupDataVenda.add(jRadioButton5);
        jRadioButton5.setText("Hoje");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroupDataVenda.add(jRadioButton6);
        jRadioButton6.setText("Outro dia");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroVenda_dataLayout = new javax.swing.GroupLayout(jPanelCadastroVenda_data);
        jPanelCadastroVenda_data.setLayout(jPanelCadastroVenda_dataLayout);
        jPanelCadastroVenda_dataLayout.setHorizontalGroup(
            jPanelCadastroVenda_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadastroVenda_dataLayout.setVerticalGroup(
            jPanelCadastroVenda_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVenda_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroVenda_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelCadastroVenda_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelCadastroVenda_quatidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelCadastroVenda_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelCadastroVenda_anos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCadastroVenda_aquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelCadastroVenda_pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelCadastroVenda_tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCadastroVenda_pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCadastroVenda_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCadastroVenda_aquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelCadastroVenda_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelCadastroVenda_anos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanelCadastroVenda_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCadastroVenda_quatidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton3)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQtdActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQtdActionPerformed

    private void jTextFieldDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDispositivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDispositivosActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        venCadOutAquisicoes.setFormaPagamento("MP");        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        venCadOutAquisicoes.setFormaPagamento("DEPOSITO");        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        venCadOutAquisicoes.setFormaAquisicao("WHATSAPP");        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        venCadOutAquisicoes.setFormaAquisicao("EMAIL");        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton3anosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3anosActionPerformed
        anoProduto = 3;         // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3anosActionPerformed

    private void jRadioButton2anosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2anosActionPerformed
        anoProduto = 2;           // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2anosActionPerformed

    private void jRadioButton1anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1anoActionPerformed
        anoProduto = 1;        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1anoActionPerformed

    private void jTextFieldApelidoCadastraVendaWhatsappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApelidoCadastraVendaWhatsappActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApelidoCadastraVendaWhatsappActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean ok = true;
        if (buttonGroupPagamento.getSelection() == null) {
            jPanelCadastroVenda_pagamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0)));
            ok = false;
        } else {
            jPanelCadastroVenda_pagamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
            ok = true;
        }
        if (buttonGroupAquisicao.getSelection() == null) {
            jPanelCadastroVenda_aquisicao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aquisição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0)));
            ok = false;
        } else {
            jPanelCadastroVenda_aquisicao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aquisição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
            ok = true;
        }
        if (jTextFieldApelidoCadastraVendaWhatsapp.getText().equals("")) {
            jPanelCadastroVenda_cliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0)));
            ok = false;
        } else {
            jPanelCadastroVenda_cliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
            ok = true;
        }
        if (buttonGroupDataVenda.getSelection() == null) {
            jPanelCadastroVenda_data.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0)));
            ok = false;
        } else {
            jPanelCadastroVenda_data.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
            ok = true;
        }
        if (buttonGroupTipo.getSelection() == null) {
            jPanelCadastroVenda_tipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0)));
            ok = false;
        } else {
            jPanelCadastroVenda_tipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
            ok = true;
        }
        if (buttonGroupAnos.getSelection() == null) {
            jPanelCadastroVenda_anos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Anos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0)));
            ok = false;
        } else {
            jPanelCadastroVenda_anos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Anos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
            ok = true;
        }
        if (jTextFieldQtd.getText().equals("") || jTextFieldValor.getText().equals("") || jTextFieldDispositivos.getText().equals("")) {
            jPanelCadastroVenda_quatidade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quantidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0)));
            ok = false;
        } else {
            jPanelCadastroVenda_quatidade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quantidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
            ok = true;
        }
        if (VariaveisDeControle.frameCadastroClienteAberto) {

        }
        if (ok) {
            new Thread(() -> {
                VendaDAO vDao = new VendaDAO();
                String pluralDispositivo = "dispositivos";
                String pluralAno = "anos";
                if (Integer.parseInt(jTextFieldDispositivos.getText()) == 1) {
                    pluralDispositivo = "dispositivo";
                }
                if (anoProduto == 1) {
                    pluralAno = "ano";
                }
                String nomeProduto = tipoDeProduto + " " + jTextFieldDispositivos.getText() + " " + pluralDispositivo + " " + anoProduto + " " + pluralAno;
                System.out.println(nomeProduto);
                venCadOutAquisicoes.setIdProduto(new ProdutosDAO().pegaIDProduto(nomeProduto));
                venCadOutAquisicoes.setApelido_comprador(jTextFieldApelidoCadastraVendaWhatsapp.getText());
                venCadOutAquisicoes.setValor(Double.parseDouble(jTextFieldValor.getText()));
                venCadOutAquisicoes.setCadastroVendedor(1);
                venCadOutAquisicoes.setFormaAquisicao("WHATSAPP");
                venCadOutAquisicoes.setFormaPagamento("DEPOSITO");
                venCadOutAquisicoes.setId(vDao.getCountVendasWhatsappDoDia());
                venCadOutAquisicoes.setQtd(Integer.parseInt(jTextFieldQtd.getText()));
                venCadOutAquisicoes.setValor(Double.parseDouble(jTextFieldValor.getText()));
                venCadOutAquisicoes.setHora(new Time(System.currentTimeMillis()) + "");
                vDao.insertVendas(venCadOutAquisicoes);
            }).start();
        } else {
            JOptionPane.showMessageDialog(null, "Verifique os campos em vermelho e preencha");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButtonKISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonKISActionPerformed
        jRadioButton2anos.setVisible(false);
        jRadioButton3anos.setVisible(false);
        tipoDeProduto = "internet security";

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonKISActionPerformed

    private void jRadioButtonAndroidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAndroidActionPerformed
        jRadioButton2anos.setVisible(true);
        jRadioButton3anos.setVisible(true);
        tipoDeProduto = "android";// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAndroidActionPerformed

    private void jRadioButtonSmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSmallActionPerformed
        jRadioButton3anos.setVisible(false);
        tipoDeProduto = "small";// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSmallActionPerformed

    private void jRadioButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTotalActionPerformed
        jRadioButton2anos.setVisible(true);
        jRadioButton3anos.setVisible(true);
        tipoDeProduto = "total security";// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTotalActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        Date data = new Date(System.currentTimeMillis());
        SimpleDateFormat formatarDate = new SimpleDateFormat("yyyy-MM-dd");
        venCadOutAquisicoes.setData(formatarDate.format(data));        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        venCadOutAquisicoes.setData(JOptionPane.showInputDialog("Qual dia? 'AAAA-MM-DD'"));        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
VariaveisDeControle.frameCadVenOutroMeioAberto = false;        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAnos;
    private javax.swing.ButtonGroup buttonGroupAquisicao;
    private javax.swing.ButtonGroup buttonGroupDataVenda;
    private javax.swing.ButtonGroup buttonGroupPagamento;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCadastroVenda_anos;
    private javax.swing.JPanel jPanelCadastroVenda_aquisicao;
    private javax.swing.JPanel jPanelCadastroVenda_cliente;
    private javax.swing.JPanel jPanelCadastroVenda_data;
    private javax.swing.JPanel jPanelCadastroVenda_pagamento;
    private javax.swing.JPanel jPanelCadastroVenda_quatidade;
    private javax.swing.JPanel jPanelCadastroVenda_tipo;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton1ano;
    private javax.swing.JRadioButton jRadioButton2anos;
    private javax.swing.JRadioButton jRadioButton3anos;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton jRadioButtonAndroid;
    private javax.swing.JRadioButton jRadioButtonKIS;
    private javax.swing.JRadioButton jRadioButtonSmall;
    private javax.swing.JRadioButton jRadioButtonTotal;
    private javax.swing.JTextField jTextFieldApelidoCadastraVendaWhatsapp;
    private javax.swing.JTextField jTextFieldDispositivos;
    private javax.swing.JTextField jTextFieldQtd;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
