/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Datas;
import Controle.VariaveisDeControle;
import DAO.AtendentesDAO;
import DAO.ClienteDAO;
import DAO.CodigoDAO;
import DAO.DesbloqueioDAO;
import DAO.IncidentesDAO;
import EmailConfig.AssuntosEmail;
import EmailConfig.MensagensEmail;
import Entidades.Atendentes;
import Entidades.Cliente;
import Entidades.Codigos;
import Entidades.Desbloqueios;
import Entidades.Incidentes;
import Entidades.Vendas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import org.joda.time.Days;
import org.joda.time.LocalDate;

/**
 *
 * @author Joao
 */
public class InternalFrameCodigos extends javax.swing.JInternalFrame {

    private String situacao;
    private String tipo;
    DefaultTableModel modelo1;
    DefaultTableModel modelo2;
    private String local;
    private int idCodigo;
    private String dataDesbloqueio;
    private String hora;
    private int qtd_usada;
    private ArrayList<Atendentes> listAtendentes = new ArrayList<>();

    /**
     * Creates new form InternalFrameCodigos
     */
    public InternalFrameCodigos() {
        modelo1 = new DefaultTableModel(null, new String[]{"Id", "Codigo", "Pedido", "Data Compra", "Dias Restantes", "Qtd Usada",
            "Tipo", "Dispositivos", "Anos", "Nome", "Email", "Suspeito de revenda", "Senha MyKaspersky"}) {
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };
        modelo2 = new DefaultTableModel(null, new String[]{"Atendente", "Qtd_usada", "Data", "Hora", "Local", "Motivo", "Pais", "Resolvido"});
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSituacaoCodigo = new javax.swing.ButtonGroup();
        buttonGroupDiaDesbloqueio = new javax.swing.ButtonGroup();
        buttonGroupLocalDesbloquei = new javax.swing.ButtonGroup();
        jDialogsetDesbloqueio = new javax.swing.JDialog();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButtonSim = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jDialogGetDesbloqueios = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        buttonGroupResolvido = new javax.swing.ButtonGroup();
        jPanelCodigos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCodigos = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jTextFieldEntradaCodigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jComboBoxAnos = new javax.swing.JComboBox<>();
        jRadioButton12 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButtonExpirando = new javax.swing.JRadioButton();

        jDialogsetDesbloqueio.setMinimumSize(new java.awt.Dimension(700, 500));
        jDialogsetDesbloqueio.setModal(true);

        buttonGroupDiaDesbloqueio.add(jRadioButton14);
        jRadioButton14.setText("Hoje");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        buttonGroupDiaDesbloqueio.add(jRadioButton15);
        jRadioButton15.setText("Outro dia");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });

        try{
            listAtendentes = new AtendentesDAO().retornaAtendentes();
            jList1.setModel(new javax.swing.AbstractListModel<String>() {

                public int getSize() { return listAtendentes.size();
                }
                public String getElementAt(int i) { return (listAtendentes.get(i).getNome()+ " ----- Pais: " + listAtendentes.get(i).getPais()); }
            });
        }catch(Exception e){

        }
        jScrollPane4.setViewportView(jList1);

        jLabel15.setText("Atendentes");

        jButton9.setText("SALVAR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        buttonGroupLocalDesbloquei.add(jRadioButton16);
        jRadioButton16.setText("Por ligação");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });

        buttonGroupLocalDesbloquei.add(jRadioButton17);
        jRadioButton17.setText("Pelo MyKaspersky");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });

        jLabel16.setText("Motivo:");

        jLabel17.setText("Resolvido:");

        buttonGroupLocalDesbloquei.add(jRadioButton18);
        jRadioButton18.setText("Pelo Chat");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });

        buttonGroupResolvido.add(jRadioButtonSim);
        jRadioButtonSim.setText("SIM");

        buttonGroupResolvido.add(jRadioButton2);
        jRadioButton2.setText("NÃO");

        javax.swing.GroupLayout jDialogsetDesbloqueioLayout = new javax.swing.GroupLayout(jDialogsetDesbloqueio.getContentPane());
        jDialogsetDesbloqueio.getContentPane().setLayout(jDialogsetDesbloqueioLayout);
        jDialogsetDesbloqueioLayout.setHorizontalGroup(
            jDialogsetDesbloqueioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogsetDesbloqueioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogsetDesbloqueioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogsetDesbloqueioLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDialogsetDesbloqueioLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jDialogsetDesbloqueioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogsetDesbloqueioLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jDialogsetDesbloqueioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogsetDesbloqueioLayout.createSequentialGroup()
                                        .addGroup(jDialogsetDesbloqueioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialogsetDesbloqueioLayout.createSequentialGroup()
                                                .addGroup(jDialogsetDesbloqueioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialogsetDesbloqueioLayout.createSequentialGroup()
                                                        .addGroup(jDialogsetDesbloqueioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jRadioButton16)
                                                            .addComponent(jRadioButton14))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(jDialogsetDesbloqueioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jDialogsetDesbloqueioLayout.createSequentialGroup()
                                                                .addComponent(jRadioButton17)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jRadioButton18))
                                                            .addComponent(jRadioButton15)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialogsetDesbloqueioLayout.createSequentialGroup()
                                                        .addComponent(jLabel17)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jRadioButtonSim)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jRadioButton2)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(26, 26, 26))
                                    .addGroup(jDialogsetDesbloqueioLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogsetDesbloqueioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))))))
        );
        jDialogsetDesbloqueioLayout.setVerticalGroup(
            jDialogsetDesbloqueioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogsetDesbloqueioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addGroup(jDialogsetDesbloqueioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogsetDesbloqueioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)
                        .addGap(45, 45, 45))
                    .addGroup(jDialogsetDesbloqueioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jDialogsetDesbloqueioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton16)
                            .addComponent(jRadioButton17)
                            .addComponent(jRadioButton18))
                        .addGap(18, 18, 18)
                        .addGroup(jDialogsetDesbloqueioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton14)
                            .addComponent(jRadioButton15))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jDialogsetDesbloqueioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jRadioButtonSim)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9)
                        .addGap(0, 24, Short.MAX_VALUE))))
        );

        jDialogGetDesbloqueios.setMinimumSize(new java.awt.Dimension(900, 500));
        jDialogGetDesbloqueios.setModal(true);

        jScrollPane6.setMinimumSize(new java.awt.Dimension(900, 500));

        jTable3.setModel(modelo2);
        jTable3.setMinimumSize(new java.awt.Dimension(900, 500));
        jTable3.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTable3.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTable3.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTable3.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTable3.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable3.getColumnModel().getColumn(5).setPreferredWidth(180);
        jTable3.getColumnModel().getColumn(6).setPreferredWidth(80);
        jTable3.getColumnModel().getColumn(7).setPreferredWidth(80);
        jScrollPane6.setViewportView(jTable3);

        javax.swing.GroupLayout jDialogGetDesbloqueiosLayout = new javax.swing.GroupLayout(jDialogGetDesbloqueios.getContentPane());
        jDialogGetDesbloqueios.getContentPane().setLayout(jDialogGetDesbloqueiosLayout);
        jDialogGetDesbloqueiosLayout.setHorizontalGroup(
            jDialogGetDesbloqueiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogGetDesbloqueiosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialogGetDesbloqueiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jDialogGetDesbloqueiosLayout.setVerticalGroup(
            jDialogGetDesbloqueiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogGetDesbloqueiosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Códigos");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jTableCodigos.setModel(modelo1);
        jTableCodigos.setCellSelectionEnabled(true);
        jTableCodigos.setColumnSelectionAllowed(true);
        jTableCodigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCodigosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableCodigos);
        jTableCodigos.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTableCodigos.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTableCodigos.getColumnModel().getColumn(2).setPreferredWidth(70);
        jTableCodigos.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTableCodigos.getColumnModel().getColumn(4).setPreferredWidth(70);
        jTableCodigos.getColumnModel().getColumn(5).setPreferredWidth(40);
        jTableCodigos.getColumnModel().getColumn(6).setPreferredWidth(60);
        jTableCodigos.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTableCodigos.getColumnModel().getColumn(8).setPreferredWidth(30);
        jTableCodigos.getColumnModel().getColumn(9).setPreferredWidth(70);
        jTableCodigos.getColumnModel().getColumn(10).setPreferredWidth(130);
        jTableCodigos.getColumnModel().getColumn(11).setPreferredWidth(70);
        jTableCodigos.getColumnModel().getColumn(12).setPreferredWidth(70);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa por código"));

        jButton5.setText("Pesquisar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel14.setText("Código:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldEntradaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jTextFieldEntradaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa por tipo de código"));

        buttonGroupSituacaoCodigo.add(jRadioButton11);
        jRadioButton11.setText("Utilizando");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KIS", "TOTAL", "SMALL", "ANTIVIRUS", "ANDROID" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jComboBoxAnos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 ano", "2 anos", "3 anos", "4 anos", "5 anos" }));
        jComboBoxAnos.setSelectedItem("Ano");
        jComboBoxAnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnosActionPerformed(evt);
            }
        });

        buttonGroupSituacaoCodigo.add(jRadioButton12);
        jRadioButton12.setText("Outra situacao");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        jButton6.setText("Pesquisar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        buttonGroupSituacaoCodigo.add(jRadioButton13);
        jRadioButton13.setText("Todos");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        buttonGroupSituacaoCodigo.add(jRadioButtonExpirando);
        jRadioButtonExpirando.setText("Expirando");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxAnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonExpirando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton11)
                    .addComponent(jComboBoxAnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton12)
                    .addComponent(jButton6)
                    .addComponent(jRadioButton13)
                    .addComponent(jRadioButtonExpirando))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelCodigosLayout = new javax.swing.GroupLayout(jPanelCodigos);
        jPanelCodigos.setLayout(jPanelCodigosLayout);
        jPanelCodigosLayout.setHorizontalGroup(
            jPanelCodigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCodigosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCodigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1219, Short.MAX_VALUE)
                    .addGroup(jPanelCodigosLayout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCodigosLayout.setVerticalGroup(
            jPanelCodigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCodigosLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanelCodigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1259, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelCodigos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelCodigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        pesquisarTodosCodigos(modelo1);
        // TODO add your handling code here
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        situacao = "and situacao = 'utilizando'";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jComboBoxAnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnosActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAnosActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        situacao = " and situacao != 'utilizando' ";
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        pesquisarTodosCodigosPorTipo(modelo1);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        situacao = "";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        Date data = new Date(System.currentTimeMillis());
        SimpleDateFormat formatarDate = new SimpleDateFormat("yyyy-MM-dd");
        dataDesbloqueio = formatarDate.format(data);
        Time time = new Time(System.currentTimeMillis());
        hora = time + "";

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        dataDesbloqueio = JOptionPane.showInputDialog("Qual dia? 'AAAA-MM-DD'");
        Time time = new Time(System.currentTimeMillis());
        hora = time + "";
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Desbloqueios des = new Desbloqueios();
        des.setId_atendente(listAtendentes.get(jList1.getSelectedIndex()).getId());
        des.setId_codigo(idCodigo);
        des.setQtd_usada(qtd_usada);
        des.setData(dataDesbloqueio);
        des.setHora(hora);
        des.setLocal(local);
        des.setPais(listAtendentes.get(jList1.getSelectedIndex()).getPais());
        des.setMotivo(jTextArea1.getText());
        if (jRadioButtonSim.isSelected()) {
            des.setResolvido("SIM");
        } else {
            des.setResolvido("NÂO");
        }
        try {
            new DesbloqueioDAO().setDesbloqueio(des);
            JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!");
            ArrayList<Incidentes> array = new IncidentesDAO().getIncidentesPorIdCodigo(idCodigo);
            array.forEach(inc -> {
                new Thread(() -> {
                    new Controle.ControleIncidentes().encerrarIncidente(inc.getId(), null, false);
                }).start();
            });
            jDialogsetDesbloqueio.dispose();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        local = "CALL";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        local = "MYKAS";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        local = "Chat";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        VariaveisDeControle.frameCodigosAberto = false;        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing

    private void jTableCodigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCodigosMouseClicked
        if ((evt.getModifiers() & MouseEvent.BUTTON3_MASK) != 0 && jTableCodigos.getSelectedRowCount() == 1) {
            int i = jTableCodigos.getSelectedRow();
            idCodigo = (int) jTableCodigos.getValueAt(i, 0);
            int dias_restantes = (int) jTableCodigos.getValueAt(i, 4);
            String codigo = (String) jTableCodigos.getValueAt(i, 1);
            JPopupMenu jpop = new JPopupMenu();
            JMenuItem registrarDesbloqueio = new JMenuItem("Registrar Desbloqueio");
            JMenuItem pesquisarDesbloqueios = new JMenuItem("Pesquisar Desbloqueio");
            JMenuItem mudarSituacaoCodigo = new JMenuItem("Modificar Situação");
            JMenuItem enviarEmailClientesExpiracao = new JMenuItem("Enviar Email Clientes");
            registrarDesbloqueio.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    jDialogsetDesbloqueio.setVisible(true);
                }
            });

            pesquisarDesbloqueios.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    pesquisarDesbloqueios(modelo2);
                    jDialogGetDesbloqueios.setVisible(true);
                }
            });
            mudarSituacaoCodigo.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    int i = JOptionPane.showConfirmDialog(null, "Deseja modificar a situação do código para reposição?", "Confirmar", JOptionPane.YES_NO_OPTION);
                    if (i == 0) {
                        new CodigoDAO().setSituacaoCodigo("REPOSICAO", idCodigo);
                        JOptionPane.showMessageDialog(null, "Situação modificada!");
                    }
                }
            });

            enviarEmailClientesExpiracao.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    new Thread(() -> {

                        int i = JOptionPane.showConfirmDialog(null, "Enviar email para os clientes avisando da expiração?", "Confirmar", JOptionPane.YES_NO_OPTION);
                        if (i == 0) {
                            ArrayList<Object[]> list = new ClienteDAO().getClientePorCodigo(idCodigo);
                            list.forEach((o) -> {
                                Cliente c = (Cliente) o[0];
                                Vendas v = (Vendas) o[1];
                                String corpo = new MensagensEmail().emailAvisoExpirando(c.getNome(), dias_restantes + "", v, codigo);
                                String assunto = new AssuntosEmail().lembreteExpiracao(v.getId());
                                new EmailConfig.EmailService(c.getEmail(), assunto, corpo).sendEmail(c.getApelido());
                            });
                        }
                    }).start();
                }
            });

            jpop.add(registrarDesbloqueio);
            jpop.add(pesquisarDesbloqueios);
            jpop.add(mudarSituacaoCodigo);
            if (jRadioButtonExpirando.isSelected()) {
                jpop.add(enviarEmailClientesExpiracao);
            }
            jpop.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jTableCodigosMouseClicked

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDiaDesbloqueio;
    private javax.swing.ButtonGroup buttonGroupLocalDesbloquei;
    private javax.swing.ButtonGroup buttonGroupResolvido;
    private javax.swing.ButtonGroup buttonGroupSituacaoCodigo;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBoxAnos;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JDialog jDialogGetDesbloqueios;
    private javax.swing.JDialog jDialogsetDesbloqueio;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanelCodigos;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButtonExpirando;
    private javax.swing.JRadioButton jRadioButtonSim;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTableCodigos;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldEntradaCodigo;
    // End of variables declaration//GEN-END:variables

    public void pesquisarTodosCodigos(DefaultTableModel modelo) {
        modelo.setNumRows(0);
        CodigoDAO dao = new CodigoDAO();
        String entrada = jTextFieldEntradaCodigo.getText().replaceAll("^\\s+", "");
        entrada = entrada.replaceAll("\\s+$", "");
        Codigos c = dao.getCodigosPorCodigo(entrada);
        int dias = new Datas().getDiasRestantesPartirHoje(c.getData_expiracao());
        modelo.addRow(new Object[]{c.getId(), c.getCodigo(), c.getPedido(), c.getData_compra(), dias,
            c.getQtd_usada(), c.getTipo(), c.getDispositivos(), c.getDuracao(), c.getNome(),
            c.getEmail(), c.getSuspeito(), c.getSenha_mykaspersky()});
        idCodigo = c.getId();
        qtd_usada = c.getQtd_usada();
        tipo = c.getTipo();
    }

    public void pesquisarTodosCodigosPorTipo(DefaultTableModel modelo) {
        modelo.setNumRows(0);
        CodigoDAO dao = new CodigoDAO();
        ArrayList<Codigos> list;
        if (jRadioButtonExpirando.isSelected()) {
            list = dao.getCodigosProximosExpirar();
        } else {
            list = dao.buscaTodosOsCodigos(jComboBoxTipo.getSelectedItem().toString(), situacao, jComboBoxAnos.getSelectedIndex() + 1);
        }

        if (list != null) {
            for (Codigos c : list) {

                int dias = new Datas().getDiasRestantesPartirHoje(c.getData_expiracao());
                modelo.addRow(new Object[]{c.getId(), c.getCodigo(), c.getPedido(), c.getData_compra(), dias,
                    c.getQtd_usada(), c.getTipo(), c.getDispositivos(), c.getDuracao(), c.getNome(),
                    c.getEmail(), c.getSuspeito(), c.getSenha_mykaspersky()});
                idCodigo = c.getId();
                qtd_usada = c.getQtd_usada();
                tipo = c.getTipo();
            }
        }
    }

    public void pesquisarDesbloqueios(DefaultTableModel modelo) {
        modelo.setNumRows(0);
        DesbloqueioDAO dao = new DesbloqueioDAO();
        ArrayList<Desbloqueios> list = (ArrayList) dao.getDesbloqueiosPorId(idCodigo);
        list.forEach((d) -> {
            modelo.addRow(new Object[]{d.getId_atendente(),
                d.getQtd_usada(), d.getData(), d.getHora(),
                d.getLocal(), d.getMotivo(), d.getPais(), d.getResolvido()});
        });
        setMensagemPorTipo();
    }

    public void setMensagemPorTipo() {
        String qtdMaxima = null;
        if (tipo.equals("TOTAL")) {
            qtdMaxima = "2 desbloqueios";
        }
        if (tipo.equals("KIS")) {
            qtdMaxima = "2 desbloqueios";
        }
        jLabel26.setText("O código deve ter no máximo " + qtdMaxima + " em até um mês da compra, com o resolvido 'SIM'. Caso não tenha passado um mês e ele está excedido, me avisa");
    }

}
